<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sat, 07 Mar 2015 01:33:31 +0100
 */

$conf['title'] = 'Documentation';
$conf['template'] = 'dokuwiki';
$conf['sidebar'] = 'navigation';
$conf['license'] = 'gnufdl';
$conf['breadcrumbs'] = 0;
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['passcrypt'] = 'sha512';
$conf['superuser'] = '@admin';
$conf['jpg_quality'] = 80;
$conf['htmlmail'] = 0;
$conf['rss_type'] = 'rss2';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['sepchar'] = '-';
$conf['compression'] = '0';
$conf['plugin']['indexmenu']['aclcache'] = 'user';
$conf['plugin']['indexmenu']['skip_file'] = '/(navigation|syntax)/';

// end auto-generated content
